apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
  namespace: orderhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
        - name: java-backend
          image: java-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/orders_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: KAFKA_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: java-backend
  namespace: orderhub
spec:
  selector:
    app: java-backend
  ports:
    - port: 8081
      targetPort: 8081
